camunda:
    bpm:
        client:
            base-url: http://localhost:8080/engine-rest
            subscriptions:
                testTopic:
                    lock-duration: 900000
            worker-id: hunter

server:
    port: 8090
spring:
    application:
        name: hunter